name: test-action
on:
  release:
    types: [released, prereleased]
jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Github Releases To Discord
        uses: RifkyHernanda3/test-publish-release@v1.0 # Uses an action in the root directory
        with:
          ENV_SHORTNAME: "dev"
          WEBHOOK_URL: ${{secrets.WEBHOOK_URL}}